### ISSUE TITLE
CFG: Bilder neu malen

### ISSUE THREAD

**Issue by cagix** [Compilerbau/Lecture#103]
Bitte folgende Bilder neu mit Dot oder Tikz erstellen:

- [parsbeispiel.png](https://github.com/Compilerbau/Lecture/blob/parsing/cfg/markdown/parsing/cfg/images/parsbeispiel.png) (analog zu den Abbildungen für LR, d.h. selber Farbstil etc.)
- [pda2.png](https://github.com/Compilerbau/Lecture/blob/parsing/cfg/markdown/parsing/cfg/images/pda2.png) (einfach Dot)

Im Branch [parsing/cfg](https://github.com/Compilerbau/Lecture/tree/parsing/cfg) dann die `.png` mit den `.tex` bzw. `.dot` ersetzen.

/CC @bcg7

**Comment by jposselt** [comment]
Das Automaten-Bild wurde gar nicht benutzt. Ich habe es raus genommen.

**Comment by cagix** [comment]
danke fürs nachschauen und prüfen 👍
