### ISSUE TITLE
Algorithmen als Abbildungen

### ISSUE THREAD

**Issue by cagix** [Compilerbau/Lecture#11]
Hugo kann mit TeX-Umgebungen (etwa Algorithmen) nicht umgehen. 

Abhilfe:
1. Algorithmus XYZ als `.tex`-Datei im `images/`-Ordner der Seite ablegen: `images/xyz.tex`
2. In der Seite statt des Algorithmus' XYZ die Abbildung `images/xyz.png` einbinden
2. Vor dem Hugo-Lauf als Vorverarbeitungsschritt alle `images/xyz.tex` nach `images/xyz.png` mit einem geeigneten Latex-Docker-Image übersetzen
3. Pandoc-Lauf zum Generieren der Folien nimmt dann das Bild
4. Hugo-Lauf zum Generieren der Webseite nimmt dann das Bild

Sinnvollerweise sollten diese Dateien automatisch gefunden und übersetzt werden (Makefile, GH-Action).

Es sollte ein Grundgerüst für diese Dateien angelegt werden als Hugo-Archetyp (auch wenn man das vermutlich nie mit Hugo anlegen wird, aber dann kann man das manuell rüberkopieren).

@Compilerbau/core

**Comment by jposselt** [comment]
Ich habe den Workflow für Hugo in meinem Test-Repo implementiert. Das Docker-Image für die Bearbeitung der Tex-Dateien müsste man aber noch austauschen. Ich hatte irgendeins genommen, dass die benötigten Programme hat (Latex und Ghostscript).
Das Image, das du sonst für die CB Vorlesung benutzt hast würde auch gehen. Wenn man damit nur die Tex-Dateien in Bilder umwandeln will, könnte man es wahrscheinlich noch kleiner machen.

**Comment by cagix** [comment]
@jposselt alles klar, ich übertrage das mal und probiere das aus. danke dir :)

**Comment by cagix** [comment]
done with commit https://github.com/KI-Vorlesung/kitest/commit/59e70099897d1e6440d51f9983a7b88b0b3ba46e  in https://github.com/KI-Vorlesung/kitest/issues/20
