### ISSUE TITLE
[BUG] von pdflatex generierte PDF-Dateien scheinen fehlerhaft zu sein.

### ISSUE THREAD

**Issue by bcg7** [Compilerbau/Lecture#118]
Wen ich diese Dateien mit xournal++ annotiere, wird anschließend eine leere PDF-Seite exportiert. Es scheint am PDf selbst zu liegen: Wenn ich die Ausgangs-PDF-Datei vor dem Annotieren in Libre-Office-Draw einlae und als PDF speichere, lässt sie sich anschließend ganz normal weiterverarbeiten. Einlesen und Speichern mit Okular löst das Problem nicht.

**Comment by cagix** [comment]
@bcg7 Die PDFs stammen aus der Toolchain im Docker, oder?

**Comment by cagix** [comment]
Könnte das was mit Fonts zu tun haben? Kann man (mit `pdflatex`) Fonts in das generierte PDF einbetten?

**Comment by bcg7** [comment]
Es betrifft die DAteien aus dem docker und solche, die ich mit 
texstudio erzeuge. Ich browse gerade durch die 681 Bugs, die im github für xournal++ gemeldet wurden. Da gibt es zumindest einen nicht ganz identischen Fall, der tatsächlich mit Fonts zu tun haben scheint. Der wird gerade auch bearbeitet.

**Comment by bcg7** [comment]
Es ist definitiv ein xournal++-Bug. Ich habe eine alte von mir bereits erfolgreich annotierte und exportierte Datei mit xournal++ geöffnet und nach pdf exportiert: dasselbe Problem.
Ich mache bei denen ein Ticket auf.

**Comment by cagix** [comment]
ah, ok. das wäre das nächste gewesen: ob du direkt mit latex und ohne irgendwelche shenanigans ein pdf erzeugen und annotieren kannst. durch beamer und das metropolis-theme kommt ja schon ne menge kram mit in die pdfs ...
