### ISSUE TITLE
Kleine Verbesserung am Makefile

### ISSUE THREAD

**Issue by jposselt** [Compilerbau/Lecture#124]
https://github.com/Compilerbau/Lecture/blob/78a1264bf15463b5c846d2e00ac1367ba3aba90e/Makefile#L242-L251

ändern in

```
## Canned recipe for creating output folder
define create-folder
@mkdir -p $(dir $@)
endef

## Canned recipe for creating output folder and copy output file
define create-dir-and-copy
$(create-folder)
cp $< $@
endef
```

Effekt:

- Codeduplikat entfernt
- weniger _noise_ im Output (`mkdir` Kommando ist stumm)

**Comment by cagix** [comment]
fixed in c232797
