### ISSUE TITLE
GH-Package für Docker Images

### ISSUE THREAD

**Issue by cagix** [Compilerbau/Lecture#19]
Ich habe in https://github.com/KI-Vorlesung/kitest/tree/master/.github/actions/alpine-pandoc-hugo eine eigene GH-Action "alpine-pandoc-hugo" definiert, die on-the-fly ein Docker-Image baut basierend auf dem `Dockerfile` in diesem Ordner. Die Workflows, die diese Aktion einsetzen, bauen also zuerst automatisch das Image. 

Das Image basiert auf `pandoc/docker` und fügt noch ein paar TeX-Pakete hinzu, die für das Erzeugen von Folien benötigt werden. Wo ich dann schon mal dabei war, füge ich auch noch Hugo hinzu. So kann man ein Image einfach für alle unsere Aufgaben nutzen.

Der Nachteil ist, dass das Bauen des Images ca. 14 Sekunden braucht. Das ist akzeptabel, wenn die Webseite im Hintergrund neu gebaut und deployed wird. Wenn man aber nur einen Foliensatz neu bauen will, um beispielsweise die Formatierungen zu testen, dauert das zu lange. 

Der Ausweg könnten "GH-Packages" sein. Da gibt es auch eine eigene Containter-Registry, wo man das selbst gebaute Image hinterlegen könnte und dann in der GH-Action von dort einfach abrufen könnte.

Der Startpunkt könnte https://github.blog/2020-09-01-introducing-github-container-registry/ sein. Die Beschreibungen sind allerdings ziemlich umständlich und es werden viele Actions eingesetzt, deren Sinn sich nicht direkt erschließt.

@jposselt @AMatutat Könnt ihr euch damit bitte beschäftigen? Ziel sollte sein, ein Grundverständnis aufzubauen und die tatsächlich essentiellen Schritte zu identifizieren, um dann zu entscheiden, ob wir das einsetzen oder nicht.

**Comment by jposselt** [comment]
Ich habe das Erstellen und Benutzen eines Image mal in einem [Test-Repo](https://github.com/jposselt/test-container) ausprobiert. Ist eigentlich nicht schwierig.

Wenn man nur Formatierungen zu testen will, sollte man das aber besser auf einem lokalen Rechner machen, da eine GH-Action immer einen gewissen Overhead hat und weniger flexibel in der Ausführung ist. Dafür ist es aber auch sinnvoll das Docker-Image zu haben, so dass man das nicht selber bauen muss (was bei mir ja nicht so richtig funktioniert hat).

**Comment by cagix** [comment]
@jposselt Sieht gut aus :)

Du verwendest ein `secrets.REGISTRY_TOKEN` (in `password: ${{ secrets.REGISTRY_TOKEN }}`). Musst Du das irgendwo anlegen? (Wenn ja, wie und wo?)

**Comment by jposselt** [comment]
Das ist ein [Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) mit Scopes für **repo** and **write:packages**. Ich habe aber gerade gesehen, dass das `GITHUB_TOKEN` auch gehen sollte. Die Anleitung, die ich benutzt habe, ist in dem Punkt anscheinend veraltet.

Die [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) (`ghcr`) ist eine Variante der [GH Package](https://docs.github.com/en/packages) Registries speziell für Container Images und ersetz die Docker Registry `docker.pkg.github.com`. Im wesentlichen ist die Container Registry das selbe wie Docker Hub mit zusätzlichen Features wie z.B. [Zugriffskontrolle](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility) oder der Möglichkeit Container mit einem Repo zu [verknüpfen](https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package#connecting-a-repository-to-a-user-owned-container-image-on-github).

**Comment by jposselt** [comment]
Ich schließe das erst mal, da sich kein Geschwindigkeitsvorteil ergeben hat.
