### ISSUE TITLE
Docker und Hugo-Server

### ISSUE THREAD

**Issue by cagix** [Compilerbau/Lecture#33]
Wie kann ich einen Hugo-Server im Docker-Container von außen nutzen?

@jposselt Bitte hier kurz dokumentieren und dann das Ticket schließen :)

**Comment by jposselt** [comment]
`docker run -it --rm -u "$(id -u):$(id -g)" -p 1313:1313 -w "${PWD}" -v "${PWD}":"${PWD}" <docker_image> server --bind 0.0.0.0`

**Comment by cagix** [comment]
ah, danke :) 

dann muss ich mir nur noch gedanken machen, wie ich das mit dem makefile und dem bauen "verheirate" ...
