### ISSUE TITLE
altes VL-Material und Übungsblätter übertragen

### ISSUE THREAD

**Issue by cagix** [Compilerbau/Lecture#34]
Bitte die bisherigen Materialien (VL, Übungsblätter) übertragen. 

- Dabei bitte für jede neue Einheit einen eigenen Feature-Branch vom `master` abzweigen. 
    - Branch: wie der Page-Name (ohne `markdown/` und ohne `index.md`), Beispiel: `parsing/cfg` oder `assignments/sheet02`
    - Wenn die Lesson fertig kopiert ist, bitte einen Pull-Request erstellen und an @bcg7 oder @cagix zuweisen.
- Bei den von André als kritisch markierten Inhalten (siehe internes Gitlab) nur ein "TODO" übernehmen. Gilt auch für Abbildungen ...
- Inhalte können mehr oder weniger 1:1 in die Datei `index.md` übertragen werden, Ausnahmen:
    - YAML: den alten YAML-Header bitte nicht übernehmen
    - Literaturverzeichnis: Nicht übertragen. Stattdessen die Bibtex-Keys als `key` im YAML-Header unter `readings` eintragen (ohne `@`), eventuelle Kommentare als einzeiligen String als `comment` (siehe Beispiel unten)
    - Challenges gehen in das dazu gehörige Übungsblatt in den Shortcode `<<% challenges %>>`
    - Lernziele gehen in die Datei `outcomes.md`, dabei die Stichpunkte je in die entsprechenden Shortcodes `{{% k1 %}}` ... kopieren
    - Zusammenfassung "TL;DR" geht in die Datei `tldr.md`
        - Dabei das `<div id="screencast">` nicht mit kopieren
        - Das umschließende `:::notes ... :::` ebenfalls nicht mit kopieren
    - Bei BC bei den `lstlistings` mit Math-Escape gleich eine passende `.tex`-Datei im `images/`-Unterordner anlegen und die daraus generierte Abbildung im `index.md` statt der `lstlistings`-Umgebung einbinden
    - Bei BC aus Tabular o.ä. evtl. gleich eine Markdown-Tabelle oder Stichpunktliste o.ä. machen (??) 

```
readings:
  - key: "Russell2020"
    comment: "Kapitel 2 und 3"
  - key: "Ertel2017"
```

**Comment by AMatutat** [comment]
@cagix die Konfiguration das Repo ist irgendwie kaputt, ich kann keinen Branch erstellen.
Ich würde ja einfach auf einen Fork arbeiten aber ich fürchte ein großes Durcheinander.

**Comment by cagix** [comment]
> @cagix die Konfiguration das Repo ist irgendwie kaputt, ich kann keinen Branch erstellen.
> Ich würde ja einfach auf einen Fork arbeiten aber ich fürchte ein großes Durcheinander.

@AMatutat Forken ist auch irgendwie nicht soooo sinnvoll. Stand versehentlich noch auf "read", ich habe das jetzt auf "write" gegeben (ohne Push-Rechte auf dem Master) ... Sollte also jetzt gehen :)

**Comment by AMatutat** [comment]
Kurzer Überblick:

Es fehlen noch:

- Alle Vorlesungen von BC
- Orga, Einführung und co
- VM von cagi
- Aufgabenblätter (da reicht eig ein PR für oder) 


Anmerkungen:
Im Gitlab haben wir .md für Vorlesungen für die hier kein "platz" haben. Soweit ich das einschätzen kann betrifft dies
- antlr1.md
- bison.md
- interpreter4.md
- Teile von vm (es sind insgesamt 8 Datein aber nur 6 slots im Repo)

**Comment by cagix** [comment]
> * Orga, Einführung und co

das mach ich selbst, da das auf verschiedene seiten aufgeteilt wird. 

> * VM von cagi

das mach ich auch selbst, da ich ja hier nochmal inhaltlich gröber ranwollte.


> * Aufgabenblätter (da reicht eig ein PR für oder)

ja, denke ich auch. 


> Anmerkungen:
> Im Gitlab haben wir .md für Vorlesungen für die hier kein "platz" haben. Soweit ich das einschätzen kann betrifft dies
> 
> * antlr1.md
> * bison.md
> * interpreter4.md
> * Teile von vm (es sind insgesamt 8 Datein aber nur 6 slots im Repo)

ANTLR und Bison gibts ja dieses Jahr als Vorträge seitens der Studis/Canada, deshalb bin ich unschlüssig, ob wir das hier ins Repo einarbeiten sollten? Mit `draft: true` könnten wir ein Rendering seitens Hugo verhindern. Aber die Studis, die einfach direkt im Markdown nachschauen würden, hätten dann einen einfachen Vortrag ...

Was war denn in `interpreter4.md`? Hmmm, Simulation von Speicherbereichen. Hab ich das vergessen? Naja, kann ich dann zur Not ja noch nachpflegen.

VM sollte eigentlich passen. Was war denn genau überzählig?

**Comment by AMatutat** [comment]
> das mach ich selbst, da das auf verschiedene seiten aufgeteilt wird.

alles klar

> das mach ich auch selbst, da ich ja hier nochmal inhaltlich gröber ranwollte.

roger that

> VM sollte eigentlich passen. Was war denn genau überzählig?

- vm1.md Zwischencode
- vm8.md Generierung von Maschinencode

**Comment by cagix** [comment]
> > VM sollte eigentlich passen. Was war denn genau überzählig?
> 
> 
> - vm1.md Zwischencode
> 
> - vm8.md Generierung von Maschinencode 

oh, zwischencode (vm1) hatte ich vor bc's llvm-ir geschoben, da es dort am besten passt. dann ist das noch leer, oder?

Generierung von Machinencode (vm8) war eigentlich nie so ne richtige sitzung, sondern eher so ein längerer ausblick, das lassen wir elegant unter den tisch fallen ;)

**Comment by cagix** [comment]
> 
> > > VM sollte eigentlich passen. Was war denn genau überzählig?
> > 
> > 
> > - vm1.md Zwischencode
> > 
> > - vm8.md Generierung von Maschinencode 
> 
> oh, zwischencode (vm1) hatte ich vor bc's llvm-ir geschoben, da es dort am besten passt. dann ist das noch leer, oder?

intermediate/intro ist das neue vm1 ...

**Comment by AMatutat** [comment]
> intermediate/intro ist das neue vm1 ... 

so wird nen schuh draus. Soll ich das schon befüllen oder willst du vm1 auch noch umkrempeln?

**Comment by cagix** [comment]
nee, das kannste bitte noch mit rüber kopieren :)

**Comment by cagix** [comment]
@AMatutat Tack så mycket :)

**Comment by jposselt** [comment]
Ich bin etwas verwirrt was BC Vorlesungen angeht. Im Repo sind unter der Semantischen Analyse zwei verschiedene Vorlesungen für Typprüfung und Attributgrammatiken angelegt. In den alten Unterlagen ist das ein Foliensatz. Sollen die so aufgesplittet werden? Das gleich gilt für Optimierung und Datenflussanalyse.

Unter Parsing gibt es außerdem **LR** Parser Teil 1 + 2, während das In den alten Unterlagen **LL** Parser sind. Ist das ein Fehler oder so gewollt?

**Comment by bcg7** [comment]
Wenn wir im Schedule 90 Minuten dafür veranschlagt haben, ist es 
wahrscheinlich sinnvoller, nur einen Foliensatz zu machen. Aber dazu 
habe ich am morgen noch Fragen.


Am 23.09.21 um 14:24 schrieb Jonas Posselt:

**Comment by cagix** [comment]
> Im Repo sind unter der Semantischen Analyse zwei verschiedene Vorlesungen für Typprüfung und Attributgrammatiken angelegt. In den alten Unterlagen ist das ein Foliensatz. Sollen die so aufgesplittet werden? Das gleich gilt für Optimierung und Datenflussanalyse.

ich glaube, wir hatten mal drüber gesprochen und wollten das dann auftrennen. 

der nachteil ist, dass man dann für eine vorlesung/sitzung zwei foliensätze hat. der vorteil wäre, dass die jeweiligen (web-) seiten nicht ganz so lang sind/werden und man im Menü auf der linken Seite etwas mehr Gliederung/Überblick hat.

 
> Unter Parsing gibt es außerdem **LR** Parser Teil 1 + 2, während das In den alten Unterlagen **LL** Parser sind. Ist das ein Fehler oder so gewollt?

die ll-parser hat @AMatutat schon eingebaut/überarbeitet. die **lr**-parser-vorlesung sollte tatsächlich aufgeteilt und erweitert werden, zumindest war das (wenn ich mich korrekt erinnere) der plan von @bcg7 ....

**Comment by jposselt** [comment]
@cagix Wenn wir die Webseite jetzt wieder ins ILIAS packen, soll ich dann das ganze urheberrechtliche Material gleich drin lassen?

**Comment by cagix** [comment]
> @cagix Wenn wir die Webseite jetzt wieder ins ILIAS packen, soll ich dann das ganze urheberrechtliche Material gleich drin lassen?

Klares NEIN. 

1. Die Inhalte stehen als CC-Material öffentlich auf Github (ist ja erstmal unabhängig von der Webseite)
2. Mittelfristig möchte ich eine Lösung, um die GH-Pages nutzen zu können.

**Comment by jposselt** [comment]
Alle Vorlesungen bearbeitet und warten auf Merge.
