### ISSUE TITLE
Logo und Favicon finden

### ISSUE THREAD

**Issue by cagix** [Compilerbau/Lecture#5]
@bcg7 ein handgemaltes Lambda-Symbol würde gut passen, oder?

**Comment by AMatutat** [comment]
Hab mal was gepixelt (und damit mal wieder bewiesen das ich hätte Künstler werden sollen). Ist 32x32 und müsste aufgrund der Pixelnatur eigentlich ganz gut skalierbar sein. 

![pixel_halflife](https://user-images.githubusercontent.com/32962412/129893622-b01b8195-fc12-43a3-a9c2-40efa4a7104f.jpg)

@cagix  @bcg7

**Comment by cagix** [comment]
find ich super :) 👍

**Comment by bcg7** [comment]
mir gefällt es auch.

Am 18.08.21 um 14:04 schrieb Carsten Gips:

**Comment by cagix** [comment]
@AMatutat Ich habe das mal als Logo für die GH-Organisation hochgeladen. Magst Du für das Repo einen Pullrequest stellen (das Logo als PNG-Datei im Ordner `static/images/favicon.png`)? Dann ist das offiziell auch Dein Beitrag :)
