### ISSUE TITLE
Impressum/Datenschutzerklärung

### ISSUE THREAD

**Issue by cagix** [Compilerbau/Lecture#6]
Impressum/Datenschutzerklärung

Florian hat mir zwei Generatoren empfohlen. Dabei muss man einige Fragen beantworten und bekommt ein Impressum und/oder Datenschutzerklärung generiert. Die kostenfreien Pakete/Fragen sollten reichen :)

Dabei muss man auch so Fragen beantworten: Ist YouTube eingebunden? YT in der Variante no-cookies? Fonts Awesome? Irgendwelche CDN (MathJax?!)? ... Also bitte einmal die Fragen ansehen und dann nochmal unsere generierte Webseite analysieren, was wir davon wirklich haben. (Die hier beschriebenen Beispiele wären alle auf "ja".)

Generatoren:
- https://datenschutz-generator.de/datenschutzerklaerung/
- https://www.e-recht24.de/

Danach die Dokumente bitte abgleichen und "mergen" und auch nochmal mit dem Impressum/Datenschutz von https://www.einsam-durch-corona.de/ abgleichen.

**Comment by cagix** [comment]
@jposselt @AMatutat any news?

**Comment by AMatutat** [comment]
Ich Klick mich noch schlau......

**Comment by AMatutat** [comment]
Wie sieht das eigentlich mit den GitHub Datenschutz rechten aus? Wenn ich die Webseite verwende liegt die ja bei GitHub, oder?

**Comment by cagix** [comment]
> Wie sieht das eigentlich mit den GitHub Datenschutz rechten aus? Wenn ich die Webseite verwende liegt die ja bei GitHub, oder? 

ja, die seite wird über github gehostet.

ich meine irgendwo in den dokus in github gelesen zu haben, dass die für gh-pages keine cookies setzen. aber die ip-adresse kriegen sie halt immer ...


> Wer ist eigentlich der verantwortliche? Laufen wir da noch über die FH oder sind wir freibeuter?

jain ;)  letztlich bin ich oder bc das dann. aber man kann imho nur einen angeben, also werde ich das wohl sein müssen. da das ganze für die lehre ist, würde ich meine büroadresse nehmen.

**Comment by AMatutat** [comment]
> ich meine irgendwo in den dokus in github gelesen zu haben, dass die für gh-pages keine cookies setzen. aber die ip-adresse kriegen sie halt immer ...

Hmpf da brauchen wir auch irgendwas für...... 

> jain ;) letztlich bin ich oder bc das dann. aber man kann imho nur einen angeben, also werde ich das wohl sein müssen. da das ganze für die lehre ist, würde ich meine büroadresse nehmen.

alles klar

**Comment by cagix** [comment]
> > ich meine irgendwo in den dokus in github gelesen zu haben, dass die für gh-pages keine cookies setzen. aber die ip-adresse kriegen sie halt immer ...
> 
> Hmpf da brauchen wir auch irgendwas für......

auf dieser gh-page eines redakteurs(?) von heise steht vielleicht was brauchbares: https://software-architektur.tv/datenschutzerklaerung.html

**Comment by cagix** [comment]
> auf dieser gh-page eines redakteurs(?) von heise steht vielleicht was brauchbares: https://software-architektur.tv/datenschutzerklaerung.html

@AMatutat sag mal, die erklärung dort ist recht simpel gehalten. du hast ja ein paar seiten verglichen, könnte das evtl. eine basis sein? wenn man das noch ergänzen würde um youtube, awesome fonts, google fonts, cdn von mathjax?

**Comment by AMatutat** [comment]
Puh schwer zu sagen. Also ich hab schon ein paar Erklärungen in diesen simplen style gesehen. die frage ist halt, wie rechtlich richtig die am ende des tages wirklich sind.

**Comment by cagix** [comment]
hmmm, der typ arbeitet für heise, da würde ich mal schätzen, dass der weiss, wie es geht ;) ... aber du hast schon recht, helfen tut uns das erstmal gar nicht. 

naja, wir haben uns ja vorerst für die webseite intern im ilias entschieden. d.h. das repo bleibt public + cc, also oer, nur die webseite können wir dann vorerst nicht über gh-pages nutzen. aber vielleicht finde ich irgendwo nochmal ne gute beratung.
