### ISSUE TITLE
[BUG] Docker Image: TeX Live Manager veraltet

### ISSUE THREAD

**Issue by jposselt** [Compilerbau/Lecture#60]
Das Bauen des Docker-Image schlägt fehl, weil der  im install-packages Skript verwendete TeX Live Manager nicht auf dem neusten stand ist. Ich habe es bei mir lokal schon gefixt. Pull-Request folgt in Kürze.

**Comment by cagix** [comment]
boah, das ist ja eklig. dann ist aber das als basis-image verwendete `pandoc/latex`-image irgendwie bereits out-of-date?!
