### ISSUE TITLE
[BUG] Makefile: Ausführen von LaTeX bringt Shell durcheinander

### ISSUE THREAD

**Issue by jposselt** [Compilerbau/Lecture#62]
**Describe the bug**
Sobald das Makefile einmal eine TeX-Datei bearbeitet hat, schlagen weiter Targets fehl, weil Dateien nicht gefunden werden. Wiederholte Aufrufe von make schlagen sofort fehl. Es scheint so als würde bei der Shell irgendwas kaputt gehen, da Make-Kommandos wie `$(shell pwd)` oder `$(dir $(realpath $<))` einfach nur noch einen leeren String liefern. Das Verhalten bleibt bestehen bis man die Shell neu startet. Selbst `make clean` geht nicht mehr.

**To Reproduce**
1. TeX-Datei zur Umwandlung in PNG hinzufügen
2. make ausführen
3. Konvertierung der ersten TeX-Datei ist erfolgreich, weitere Targets schlagen fehl.

**Desktop:**
 - OS: Ubuntu 20.4.2 auf Windows (WSL2)

[nfa2dfa.txt](https://github.com/Compilerbau/Lecture/files/7219661/nfa2dfa.txt)

**Comment by cagix** [comment]
hast du ein beispiel? bei mir lief das bisher immer problemlos durch?

**Comment by cagix** [comment]
> hast du ein beispiel? bei mir lief das bisher immer problemlos durch?

@jposselt Kannst Du mir bitte einen Branch geben, in dem Du gearbeitet hattest und das Problem aufgetreten ist und die Page, an der Du dran warst? Wie hast Du make aufgerufen, also mit welchem Target?

Mir scheint, dass da evtl. irgendwas anderes durcheinander gegangen sein könnte. 

Allerdings habe ich auch schon seltsames Verhalten beobachtet, beispielsweise sollte bei `make web slides` sowohl im `web`- als auch im `slides`-Target der Inhalt von `markdown/` kopiert werden, aber make macht das nur beim ersten Target (unabhängig vom OS/Shell).

**Comment by jposselt** [comment]
Du kannst den Branch lexing/regular benutzen, in dem ich die Zugehörige Vorlesung von BC bearbeitet habe. Da sind zwei TeX-Dateien für Algorithmen mit dabei.

Es kann natürlich auch sein, dass das Problem nur bei mir auftritt, weil ich ein Linux als WSL unter Windows laufen habe.

**Comment by cagix** [comment]
@jposselt Wie hast Du das gebaut? Hast Du `make slides` oder `make web` oder `make lexing/regular` aufgerufen?

**Comment by jposselt** [comment]
`make slides`

**Comment by cagix** [comment]
@jposselt Hmmm, ich hab grad nur macOS da. Hier läuft es normal durch, sowohl `make lexing/regular` als auch `make slides` (letzteres dauert halt ewig, weil dabei *alle* folien gebaut werden). 

Die Bilder werden gebaut, die Folien auch, nur die Bilder sind noch nicht in den Folien eingebunden, oder?

`make web` muss ich noch testen.

**Comment by cagix** [comment]
`make web` tut auch. 

allerdings kommen dabei teilweise komische ergebnisse raus (siehe screenshot).

1. Manche Formeln werden von Hugo/MathJax nicht korrekt umgesetzt
2. Bei der Vorverarbeitung mit Pandoc (MD->MD) wird offenbar ein Umbruch escaped und taucht dann als `<br>{=html}` auf

<img width="1351" alt="Screenshot 2021-09-24 at 11 54 17" src="https://user-images.githubusercontent.com/20356276/134655994-fe556faf-63b6-403f-8472-1b1c7fbe8afd.png">

**Comment by jposselt** [comment]
@cagix Die Bilder sollten eigentlich eingebunden sein. Kann aber sein, dass ich da noch was falsch gemacht habe. Ich konnte es ja nicht testen.

Wenn das Makefile bei dir normal funktioniert ist das eine gute Nachricht. Dann liegt es wahrscheinlich wirklich an meinem Setup.

Das mit den Formel werde ich mir nochmal ansehen.

**Comment by cagix** [comment]
oh, ja: bilder brauchen ein "!" davor, sonst sind sie nur einfache links ...

also statt `[DFA Minimierung](images/minimize_dfa.png)` einfach `![DFA Minimierung](images/minimize_dfa.png)` schreiben :)

**Comment by cagix** [comment]
wg. des `<br>`:  mach mal bitte um alle html-elemente einen schutz drum:

```
aus <br> wird
`<br>`{=markdown}
```

die seiten werden durch pandoc vorverarbeitet. dabei ist es etwas übereifrig beim escapen, d.h. beim erstellen von markdown werden einige sachen (insbesondere html-elemente) escaped, wodurch hugo damit nicht mehr klarkommt. das muss man leider manuell schützen ...

**Comment by cagix** [comment]
das makefile funktioniert seltsamerweise auch in der github-action, die ja auf einem ubuntu läuft ... könnte also wirklich was mit deinem wsl sein?

**Comment by cagix** [comment]
hugo ist mist. in der überschrift "Die Übergangsfunktion eines NFAs" bringt das zweite `\Sigma^*` hugo aus dem tritt ... `$w \in \Sigma^*, w = xa, x \in \Sigma$` kriegt hugo noch hin, `$w \in \Sigma^*, w = xa, x \in \Sigma^*$` dann schon nicht mehr ...

**Comment by cagix** [comment]
ok, das ist nicht das `^`, sondern der mehrfache `*` in der formel in der zeile :(

für die html-ansicht kann man den stern escapen, dann klappt das aber nicht mehr für die folien :((

zwei lösungsansätze:

1. auslagern als "bild"
2. mit `:::slides ... :::` und `:::notes ... :::` zwei versionen implementieren

```
::: slides
* Basis: $\delta ^*(q, \epsilon) = q\ \forall q \in Q$
* Induktion: Sei $w \in \Sigma^*, w = xa, x \in \Sigma^*, a \in \Sigma$ mit \newline
     $\delta^*(q, x) =  \{ p_1,\ \ldots,\  p_k \}, p_i \in Q$, sei \newline
     $A = \bigcup\limits_{i = 1}^k \delta(p_i, a) = \{r_1, \ldots r_m \}, r_j \in Q$. \newline

     Dann ist $\delta ^*(q, w) = \{r_1,\  \ldots\ , r_m\}$.
:::

::: notes
* Basis: $\delta ^*(q, \epsilon) = q\ \forall q \in Q$
* Induktion: Sei $w \in \Sigma^{\*}, w = xa, x \in \Sigma^{\*}, a \in \Sigma$ mit `<br>`{=markdown}

     $\delta^*(q, x) =  \{ p_1,\ \ldots,\  p_k \}, p_i \in Q$, sei `<br>`{=markdown}

     $A = \bigcup\limits_{i = 1}^k \delta(p_i, a) = \{r_1, \ldots r_m \}, r_j \in Q$. `<br>`{=markdown}

     Dann ist $\delta ^*(q, w) = \{r_1,\  \ldots\ , r_m\}$.
:::
```

**Comment by jposselt** [comment]
Statt `*` kann man in Formeln auch `\ast` verwenden. Die Ausgabe sieht identisch aus.

**Comment by cagix** [comment]
perfekt! das hatte ich völlig aus dem blick verloren ... danke!

**Comment by cagix** [comment]
das problem mit den `<br>` bleibt allerdings ...

workaround:
```
[`<br>`{=markdown}]{.notes}
```

**Comment by cagix** [comment]
@cagix **note2self**: hugo muss mittelfristig wieder raus aus der toolchain. erstelle templates mit ähnlicher funktionalität direkt für pandoc.

**Comment by cagix** [comment]
@jposselt eine alternative könnte evtl. der "canan-workflow" sein: @bcg7 erstellt ihre inhalte zwar in markdown+latex im repo, aber daraus wird nur ein foliensatz für die vorlesungssitzung generiert. im `index.md` erstellt sie nur eine kurze zusammenfassung plus den link auf den irgendwo eingecheckten annotierten foliensatz. 

dann müsste ich das makefile entsprechend anpassen, aber wir wären mit einem schlag diese ganzen hässlichen pandoc+hugo-nickeligkeiten los ... 

@bcg7 was denkst du dazu?

**Comment by cagix** [comment]
@bcg7 @jposselt @AMatutat Ich habe uns zum Speichern der (annotierten) Foliensätze ein zweites Repo angelegt: https://github.com/Compilerbau/AnnotatedSlides ... 

Der ursprünglich angedachte Workflow für @bcg7 wäre:
1. @bcg7 pflegt die Inhalte hier im Repo (https://github.com/Compilerbau/Lecture) in den jeweiligen Seiten (`index.md`)
2. Für die Listing+Math-Escape erzeugen wir TeX-Files im jeweilgen `images/`-Unterordner, im `index.md` wird ein PNG-Bild gleichen Namens eingebunden
3. Mit `make topic/subtopic/page` wird der Foliensatz generiert für die Vorlesung
4. @bcg7 annotiert diesen Foliensatz in der Vorlesung, es entsteht ein neues PDF
5. Dieses neue PDF wird im Nachbar-Repo https://github.com/Compilerbau/AnnotatedSlides eingecheckt
6. Hier im `index.md` wird im YAML-Header die Variable `attachments` passend gesetzt: `link` bekommt die URL des annotierten PDFs aus dem Nachbar-Repo (einfach im Browser anklicken und die URL rauskopieren), `name` wird als URL-Text gesetzt (also entweder anpassen oder löschen)
7. Hier im Repo für den Feature-Branch einen Pull-Request zum Mergen der neuen Seite in den `master` aufmachen und im Github/Browser auf `merge squash` klicken
8. Die Webseite für die Studis baut sich automatisch, darin ist dann der Link auf die annotierten Folien enthalten

Das funktioniert auch im "modifizierten Canan-Workflow". 

Falls die Webseite vor dem Einstellen der annotierten Folien sichtbar sein soll, muss der Feature-Branch entsprechend vorher per Pull-Request in den `master` gemergt werden (dabei dann am besten die `attachments`-Variable aus dem YAML-Header löschen, sonst wird in der Webseite ein kaputter Link angezeigt!) . Dann muss man eben später zum Ergänzen des Links nochmal einen neuen Feature-Branch aufmachen.

**Comment by cagix** [comment]
won't fix (wsl?)
