### ISSUE TITLE
Orga: Planung finalisieren: Kanada

### ISSUE THREAD

**Issue by cagix** [Compilerbau/Lecture#66]
- [ ] Zeiten festlegen
- [ ] Modus definieren

---

@bcg7 @cagix

**Comment by AMatutat** [comment]
Haben wir mittlerweile ne feste Zeit? Dann könnte ich noch ne Mail raushauen, dann wissen wir vielleicht zur nächsten Woche Bescheid.

**Comment by cagix** [comment]
> Haben wir mittlerweile ne feste Zeit? Dann könnte ich noch ne Mail raushauen, dann wissen wir vielleicht zur nächsten Woche Bescheid. 

montag 1400 bis 1715 uhr ... 

aber ich vermute, dass wir diese sitzungen später machen müssen, beispielsweise 1700 bis 1830 uhr oder 1800 bis 1930 uhr. 

am besten wäre vermutlich montag, aber andere wochentage sollten um diese uhrzeit auch gehen.

**Comment by AMatutat** [comment]
18:00 bis 19:30 klingt ganz gut, wäre 10:00 bis 11:30 für kanada.
Hab mal ne mail rausgehauen, vielleicht hab ich ja morgen zum meeting schon ne antwort.

**Comment by AMatutat** [comment]
> 18:00 bis 19:30 

passt nicht. Ich hab nochmal für 17:00-18:30 angefragt. Ansonsten müssten wir den Termin auf nen anderen Tag legen. 
Offiziell geht das CB-Praktikum bis 17:15..... naja sollten wir wohl hinkriegen.

**Comment by cagix** [comment]
> > 18:00 bis 19:30
> 
> passt nicht. Ich hab nochmal für 17:00-18:30 angefragt. Ansonsten müssten wir den Termin auf nen anderen Tag legen.
> Offiziell geht das CB-Praktikum bis 17:15..... naja sollten wir wohl hinkriegen.

was genau heisst "passt nicht"? der tag? die zeit? irgendwie fehlen mir informationen ;)

was wäre, wenn die uns was vorschlagen (tage, zeit)? ab 17.30 sind die master eigentlich jeden tag frei?

**Comment by AMatutat** [comment]
> was genau heisst "passt nicht"? der tag? die zeit? irgendwie fehlen mir informationen ;)

Das da: 

> Nelson teaches a class from 11:00am to 11:50am on Monday, Wednesday, and Friday.


Wäre die alternative. Ich würde bei möglichkeit nur gerne am montag bleiben und im best case vor 20:00Uhr. 

> was wäre, wenn die uns was vorschlagen (tage, zeit)? ab 17.30 sind die master eigentlich jeden tag frei?

**Comment by cagix** [comment]
ja, okay. dann lass uns schauen, ob nelson am montag da was für uns hat.

was wir definitiv berücksichtigen müssen: die zeitumstellung! die erfolgt afaik in kanada nicht am selben wochenende.

**Comment by cagix** [comment]
andererseits: 9:00am .. 10:30am edmonton + 8h => 17:00 .. 18:30 (de) ... das könnte doch passen, oder?

(ich weiss aber nicht, wann die im vergleich zu uns umschalten.)

**Comment by AMatutat** [comment]
> was wir definitiv berücksichtigen müssen: die zeitumstellung! die erfolgt afaik in kanada nicht am selben wochenende.

daran hab ich garnit gedacht
