### ISSUE TITLE
Überarbeitung Symboltabellen (zu KW42)

### ISSUE THREAD

**Issue by cagix** [Compilerbau/Lecture#91]
Vereinfachen der Modellierung der Symboltabellen (UML, Code), die Darstellung war angelehnt an Parr und aus meiner Sicht teilweise deutlich zu komplex. An manchen Stellen kann man vielleicht Default-Methoden etc. von Java11++ einsetzen statt der vielen Einzelvererbung (war Java6) ...

Bitte das ganze Bild im Blick behalten und eine Skizze erstellen, wie es einfacher/schöner gehen könnte :)

sollte gegen KW42 fertig werden

**Comment by Fabian-Hu** [comment]
@cagix ich wollte das morgen alles fertig machen und dann mach ich ein Snippets das ist bis Dienstag auf jedenfall fertig. Wo kann man überhaupt snippets machen ich hab da nichts gefunden.

**Comment by Fabian-Hu** [comment]
ich hab die Änderung immer unter die Überschrift, der dazugehörigen Stelle, geschrieben. Die Allgemeine Änderung war, dass umbenennen vom Interface Scope zu BaseScope und die Klasse BaseScope zu Scope. Scope hat dann noch die Unterteilung von global und local verloren. Und im Interface BaseScope werden nun die default Funktion bind() und resolve() implementiert. Dafür wurden ein paar Codebeispiele angepasst. 

Ich hab keine weiteren Klassen umbenannt. Bei ScopedSymbol wusste ich kein besseren Bezeichner.

**Comment by Fabian-Hu** [comment]
Ich hab die Namen mal umgestellt aber ich weiss grade nicht wie wir nach "oben" umsetzen wollen. Aber stimmt schon bis auf die Vererbung identisch. 

![classscopesuml](https://user-images.githubusercontent.com/32959586/137794294-6df5ff12-7073-46b2-b868-2163e156171d.png)
